

input_judge_prompt_template = """You are a design assistant whose goal is to determine the type of user input, and you can only output one number, not any useless content
If it is a design goal for an optical structure (e.g. "I need to design an optical material with a maximum depth of 333 nm. The material should transmit 58.5% of light in the 4836-12136 nm range."), output the number 1
If it is a scientific question (such as' What is the essence of light '), output the number 2
If none of them are, output the number 3

Input: {user_input}
Answer:"""

scientific_prompt_template = """You are an expert in the field of optical materials. Please answer the following questions, and your answers must meet the following requirements:
1. Accuracy: Strictly based on scientific principles or recognized research conclusions, avoiding subjective speculation.
2. Structured: Elaborate on core concepts (such as definitions, mechanisms, and applications) in order, requiring clear logic.
3. The length of the generated reply should be approximately 200 words.
Instruction:{user_input}\n
Output:"""

material_selection_template = '''
You are an expert in the field of materials science which have extensive knowledge in this area. You will obtain all the materials contained in the material library, as well as the recommended materials generated by the retrieval Augmented generation system (RAG) of the LLM. Your goal is to determine the materials used in the design based on the user's design requirements, the existing materials in the material library, and the material information recommended by the RAG system for the user. Note that your output should only be ['Material 1 ','Material 2'...'Material n'], which is a list containing the final set of recommended materials, and there is no need to output any extra content.
Example 1:
Design requirement: I want to design a structure in red color, but the structure cannot contain metal.
Existing materials in the material library: ['Ag', 'Al', 'Al2O3', 'AlN', 'Ge', 'HfO2', 'ITO', 'MgF2', 'MgO', 'Si', 'Si3N4', 'SiO2', 'Ta2O5', 'TiN', 'TiO2', 'ZnO', 'ZnS', 'ZnSe']
Recommended materials for RAG system: ['Si', 'Al', 'SiO2', 'Ge', 'ITO', 'TiO2', 'Ag', 'ZnO', 'ZnS', 'ZnSe']
Output:['Si ',' SiO2 ',' ITO ',' TiO2 ',' ZnO ',' ZnS', 'ZnSe']
Example 2:
Design requirement: I want to design a dielectric structure with high absorption in the 3000-4000 nm wavelength range.
Existing materials in the material library: ['Ag', 'Al', 'Al2O3', 'AlN', 'Ge', 'HfO2', 'ITO', 'MgF2', 'MgO', 'Si', 'Si3N4', 'SiO2', 'Ta2O5', 'TiN', 'TiO2', 'ZnO', 'ZnS', 'ZnSe']
Recommended materials for RAG system: ['Ag', 'Al', 'Al2O3', 'Si', 'AlN', 'Ge', 'HfO2', 'ITO', 'MgF2', 'TiN', 'TiO2', 'ZnO', 'ZnS', 'ZnSe']
Output:['Al2O3', 'AlN', 'HfO2', 'ITO', 'MgF2', 'TiN', 'TiO2', 'ZnO', 'ZnS', 'ZnSe']
Please recommend materials based on the above requirements and examples.
Design requirement:{Requirement}
Existing materials in the material library:{Materials}
Recommended materials for RAG system:{Recommended_Materials}
Output:
'''